services:
  wordpress:
    image: drw00027/vuln-wp
    container_name: wp-vuln
    restart: always
    ports:
      - "9999:80"

  db:
    image: drw00027/vuln-mysql
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"

# Optional volumes â€” can be removed since images already contain data
volumes:
  db_data:
