services:
  wordpress:
    image: drw00027/vuln-wp
    container_name: wp-vuln
    restart: always
    ports:
      - "9999:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress

  db:
    image: drw00027/vuln-mysql
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
