services:
  db:
    image: drw00027/vuln-mysql:latest
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"

  wordpress:
    image: drw00027/vuln-wp:latest
    container_name: wp-vuln
    restart: always
    depends_on:
      - db
    ports:
      - "9999:80"
